# Generated by Django 4.2.4 on 2023-09-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tasks_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время'),
        ),
    ]
