# Generated by Django 4.2.4 on 2023-09-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_tasks_date_alter_tasks_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(null=True, verbose_name='Дедлайн'),
        ),
    ]
