# Generated by Django 4.1 on 2026-09-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0002_guide_userguideprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'Гайд обучения', 'verbose_name_plural': 'Гайды обучения'},
        ),
        migrations.AlterModelOptions(
            name='userguideprogress',
            options={'verbose_name': 'Просмотр гайда', 'verbose_name_plural': 'Просмотры гайдов'},
        ),
    ]
