# Generated by Django 4.1.2 on 2024-05-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
