# Generated by Django 5.2.6 on 2025-09-26 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_todo_hide_alter_todo_id_alter_todo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='isCompleted',
            new_name='checked',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='hide',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='update_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_date',
            field=models.DateField(default=datetime.date(2025, 9, 26)),
            preserve_default=False,
        ),
    ]
