"""Import Apple PNGs from Emojigraph; standard library only, never at startup.

python scripts/import_apple_emoji.py                 # current catalogue
python scripts/import_apple_emoji.py --from-manifest # pinned source URLs
python scripts/import_apple_emoji.py --verify        # offline integrity check
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
import hashlib
from html.parser import HTMLParser
import json
from pathlib import Path
import re
import struct
import time
from urllib.request import Request, urlopen

SOURCE = 'https://emojigraph.org/ru/apple/'
ROOT = Path(__file__).resolve().parents[1] / 'chat/static/chat/emoji/apple'
MANIFEST = ROOT / 'sources.json'
PATTERN = re.compile(r'/media/144/apple/[^/]+_([0-9a-f-]+)\.png$')


def codepoints(value):
    """Remove hex padding, preserving every actual Unicode codepoint."""
    return '-'.join(format(int(part, 16), 'x') for part in value.split('-'))


class Catalogue(HTMLParser):
    def __init__(self):
        super().__init__()
        self.assets = {}

    def handle_starttag(self, tag, attrs):
        if tag != 'img':
            return
        for path in dict(attrs).get('srcset', '').split(','):
            path = path.strip().split(' ')[0]
            match = PATTERN.fullmatch(path)
            if match:
                key = codepoints(match[1])
                url = 'https://emojigraph.org' + path
                if key in self.assets and self.assets[key] != url:
                    raise ValueError(f'Ambiguous source: {key}')
                self.assets[key] = url


def download(url):
    for attempt in range(3):
        try:
            request = Request(url, headers={'User-Agent': 'HabitusEmojiAssetImporter/1.0'})
            with urlopen(request, timeout=30) as response:
                return response.read()
        except OSError:
            if attempt == 2:
                raise
            time.sleep(attempt + 1)


def png_size(data):
    if (data[:16] != b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR'
            or data[-12:] != b'\x00\x00\x00\x00IEND\xaeB`\x82'):
        raise ValueError('Incomplete or non-PNG response')
    return struct.unpack('>II', data[16:24])


def index_module(assets):
    ids = sorted(assets)
    lines = [' '.join(ids[i:i + 12]) for i in range(0, len(ids), 12)]
    return ('// Generated by scripts/import_apple_emoji.py; do not edit.\n'
            'export const appleEmojiIds = `\n' + '\n'.join(lines) + '\n`.trim().split(/\\s+/);\n')


def verify(manifest):
    ids = manifest['assets']
    if not ids or {p.stem for p in ROOT.glob('*.png')} != set(ids):
        raise ValueError('PNG files and manifest differ')
    normalized = set()
    for key, asset in ids.items():
        if codepoints(key) != key:
            raise ValueError(f'Non-canonical filename: {key}')
        alias = '-'.join(part for part in key.split('-') if part != 'fe0f')
        if alias in normalized:
            raise ValueError(f'Ambiguous presentation-selector alias: {key}')
        normalized.add(alias)
        data = (ROOT / f'{key}.png').read_bytes()
        if png_size(data) != (144, 144):
            raise ValueError(f'Unexpected resolution: {key}')
        if hashlib.sha256(data).hexdigest() != asset['sha256']:
            raise ValueError(f'Checksum mismatch: {key}')
    if (ROOT / 'index.js').read_text(encoding='utf-8') != index_module(ids):
        raise ValueError('Generated JS index is stale')
    print(f'Verified {len(ids)} local 144x144 PNGs and generated index.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--from-manifest', action='store_true')
    parser.add_argument('--verify', action='store_true')
    parser.add_argument('--workers', type=int, choices=range(1, 9), default=6)
    args = parser.parse_args()
    if args.verify:
        verify(json.loads(MANIFEST.read_text(encoding='utf-8')))
        return
    if args.from_manifest:
        manifest = json.loads(MANIFEST.read_text(encoding='utf-8'))
        sources = {key: asset['url'] for key, asset in manifest['assets'].items()}
    else:
        html = download(SOURCE)
        catalogue = Catalogue()
        catalogue.feed(html.decode('utf-8'))
        sources = catalogue.assets
        if len(sources) < 3000:
            raise ValueError('Unexpected catalogue structure or incomplete response')
        manifest = {'source': SOURCE, 'fetched_at': datetime.now(timezone.utc).isoformat(),
                    'catalogue_sha256': hashlib.sha256(html).hexdigest(), 'size': 144}
    ROOT.mkdir(parents=True, exist_ok=True)

    def acquire(item):
        key, url = item
        match = PATTERN.fullmatch(url.removeprefix('https://emojigraph.org'))
        if not match or codepoints(match[1]) != key:
            raise ValueError(f'Unexpected source URL: {url}')
        path = ROOT / f'{key}.png'
        pinned = manifest.get('assets', {}).get(key)
        data = path.read_bytes() if pinned and path.exists() else download(url)
        if png_size(data) != (144, 144):
            raise ValueError(f'Unexpected image size: {url}')
        digest = hashlib.sha256(data).hexdigest()
        if pinned and digest != pinned['sha256']:
            raise ValueError(f'Pinned source changed: {url}')
        path.write_bytes(data)
        return key, {'url': url, 'sha256': digest, 'bytes': len(data)}

    assets = {}
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        for index, (key, asset) in enumerate(pool.map(acquire, sorted(sources.items())), 1):
            assets[key] = asset
            if index % 250 == 0:
                print(f'Imported/checked {index}/{len(sources)}', flush=True)
    manifest['assets'] = assets
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    (ROOT / 'index.js').write_text(index_module(assets), encoding='utf-8')
    verify(manifest)


if __name__ == '__main__':
    main()
