# Generated by Django 4.2.4 on 2023-08-16 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.CharField(max_length=7, verbose_name='Месяц')),
                ('backgroundColor', models.CharField(max_length=7, verbose_name='Цвет')),
                ('color', models.CharField(max_length=7, verbose_name='Цвет текста')),
                ('marks', models.TextField(verbose_name='Отметки')),
                ('number', models.IntegerField(verbose_name='Сортировка')),
                ('isGroup', models.BooleanField(verbose_name='Это группа')),
                ('beginDay', models.IntegerField(verbose_name='Начало')),
                ('endDay', models.IntegerField(verbose_name='Конец')),
                ('isOpen', models.BooleanField(verbose_name='Раскрыта')),
                ('cellsComments', models.TextField(verbose_name='Надписи клеток')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundColor', models.CharField(max_length=7, verbose_name='Цвет сайта')),
                ('tableHeadColorWeekend', models.CharField(max_length=7, verbose_name='Цвет выходных')),
                ('tableHeadColor', models.CharField(max_length=7, verbose_name='Цвет заголовка таблицы')),
                ('tableHeadTextColor', models.CharField(max_length=7, verbose_name='Цвет текста заголовка таблицы')),
                ('showCalendar', models.BooleanField(verbose_name='Показать календарь')),
                ('showCreateActivity', models.BooleanField(verbose_name='Показать создание активности')),
                ('showCreateActivityGroup', models.BooleanField(verbose_name='Показать создание группы активностей')),
                ('showDeleteActivity', models.BooleanField(verbose_name='Показать удаление активностей')),
                ('enableSortTable', models.BooleanField(verbose_name='Включить перетаскивание строк')),
                ('enableOpenCloseGroups', models.BooleanField(verbose_name='Включить открытие/закрытие групп')),
                ('showDeleteAllActivities', models.BooleanField(verbose_name='Показать кнопку удаления всех активностей')),
            ],
            options={
                'verbose_name': 'Настройку',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='ActivitiesConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='hwyd.activities', verbose_name='Активность')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='hwyd.activities', verbose_name='Группа')),
            ],
        ),
    ]
