# Generated by Django 4.2.4 on 2023-08-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='font',
            field=models.TextField(default='', verbose_name='Шрифт'),
            preserve_default=False,
        ),
    ]
