# Generated by Django 4.2.4 on 2023-08-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0002_settings_font'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='font',
        ),
        migrations.AddField(
            model_name='settings',
            name='fontFamily',
            field=models.TextField(default='', verbose_name='Семья шрифта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='fontPath',
            field=models.TextField(default='', verbose_name='Путь шрифта'),
            preserve_default=False,
        ),
    ]
