# Generated by Django 4.2.4 on 2023-12-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0002_alter_customfieldsuser_lastactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldsuser',
            name='lastActive',
            field=models.DateTimeField(),
        ),
    ]
