# Generated by Django 4.2.4 on 2023-08-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0002_activities_user_activitiesconnection_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='onSounds',
            field=models.BooleanField(default=True, verbose_name='Включить звуки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='rowColumnLight',
            field=models.CharField(default='#e7e7e7', max_length=7, verbose_name='Цвет выделения стоки и столбца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='showActivityDayLight',
            field=models.BooleanField(default=True, verbose_name='Включить выделение активности и дня'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='showRowColumnLight',
            field=models.BooleanField(default=True, verbose_name='Включить выделение строки и столбца'),
            preserve_default=False,
        ),
    ]
