# Generated by Django 4.2.4 on 2023-08-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0003_settings_onsounds_settings_rowcolumnlight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitiesconnection',
            options={'verbose_name': 'Связь активностей', 'verbose_name_plural': 'Связи активностей'},
        ),
        migrations.AddField(
            model_name='activities',
            name='onOffCells',
            field=models.TextField(default='True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True True', verbose_name='Выключение клеток'),
            preserve_default=False,
        ),
    ]
