# Generated by Django 4.2.4 on 2023-08-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0003_remove_settings_font_settings_fontfamily_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='fontPath',
        ),
        migrations.AlterField(
            model_name='settings',
            name='fontFamily',
            field=models.TextField(verbose_name='Шрифт'),
        ),
    ]
