# Generated by Django 4.2.4 on 2023-08-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0004_alter_activitiesconnection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='fontFamily',
            field=models.TextField(default='Consolas', verbose_name='Шрифт'),
            preserve_default=False,
        ),
    ]
