# Generated by Django 4.2.4 on 2023-09-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0005_settings_showopenallgroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='showOpenAllGroups',
            field=models.BooleanField(verbose_name='Открыть/закрыть группы'),
        ),
    ]
