# Generated by Django 4.2.4 on 2023-09-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0006_alter_settings_showopenallgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='showTabs',
            field=models.BooleanField(default=False, verbose_name='Вкладки'),
            preserve_default=False,
        ),
    ]
