# Generated by Django 4.2.4 on 2023-09-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0007_settings_showtabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Спрятать'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='selected',
            field=models.BooleanField(default=True, verbose_name='Выбрана настройка'),
            preserve_default=False,
        ),
    ]
