# Generated by Django 4.2.4 on 2023-12-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0009_customfieldsuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfieldsuser',
            options={'verbose_name': 'Кастомные поля', 'verbose_name_plural': 'Кастомные поля'},
        ),
        migrations.AddField(
            model_name='customfieldsuser',
            name='answers',
            field=models.TextField(default='', verbose_name='Ответы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customfieldsuser',
            name='lastActive',
            field=models.DateTimeField(verbose_name='Последнее посещение'),
        ),
    ]
