# Generated by Django 4.2.4 on 2024-04-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0010_alter_customfieldsuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='vanishing',
            field=models.CharField(default='Выключено', max_length=50, verbose_name='Тип исчезновения'),
            preserve_default=False,
        ),
    ]
