# Generated by Django 5.2.6 on 2025-10-06 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0011_settings_vanishing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата посещения')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='Первое посещение')),
                ('last_visit', models.DateTimeField(auto_now=True, verbose_name='Последнее посещение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог активности пользователя',
                'verbose_name_plural': 'Логи активности пользователей',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
