# Generated by Django 5.2.6 on 2026-02-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0012_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='backgroundColor',
            field=models.CharField(max_length=7, verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='enableOpenCloseGroups',
            field=models.BooleanField(verbose_name='Открытие/закрытие групп'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='enableSortTable',
            field=models.BooleanField(verbose_name='Перетаскивание привычек'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='onSounds',
            field=models.BooleanField(verbose_name='Звуки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='rowColumnLight',
            field=models.CharField(max_length=7, verbose_name='Выделение стоки и столбца'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='showActivityDayLight',
            field=models.BooleanField(verbose_name='Выделение привычки и дня'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='showCalendar',
            field=models.BooleanField(verbose_name='Календарь'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='showCreateActivity',
            field=models.BooleanField(verbose_name='Создание привычки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='showCreateActivityGroup',
            field=models.BooleanField(verbose_name='Создание групп привычек'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='showDeleteActivity',
            field=models.BooleanField(verbose_name='Удаление привычек'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='showDeleteAllActivities',
            field=models.BooleanField(verbose_name='Кнопка удаления всех привычек'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='showRowColumnLight',
            field=models.BooleanField(verbose_name='Выделение строки и столбца'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='showTabs',
            field=models.BooleanField(verbose_name='Проценты'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tableHeadColor',
            field=models.CharField(max_length=7, verbose_name='Фон заголовка таблицы'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tableHeadColorWeekend',
            field=models.CharField(max_length=7, verbose_name='Выходные'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tableHeadTextColor',
            field=models.CharField(max_length=7, verbose_name='Текст заголовка таблицы'),
        ),
    ]
