# Generated by Django 5.2.6 on 2026-02-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0013_alter_settings_backgroundcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Часовой пояс'),
        ),
    ]
