# Generated by Django 5.2.6 on 2026-02-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hwyd', '0014_useractivitylog_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='first_visit',
            field=models.DateTimeField(verbose_name='Первое посещение (UTC)'),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='last_visit',
            field=models.DateTimeField(verbose_name='Последнее посещение (UTC)'),
        ),
    ]
